
---
  apiVersion: v1
  kind: Pod
  metadata:
    name: stac
    labels:
      app: stac
  spec:
    containers:
      - name: pgstac
        image: ghcr.io/stac-utils/pgstac:v0.7.1
        command: ["docker-entrypoint.sh"]
        args: ["postgres", "-N", "500"]
        securityContext:
          runAsUser: 999
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "username"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "postgis"
        - name: PGUSER
          value: "username"
        - name: PGPASSWORD
          value: "password"
        - name: PGDATABASE
          value: "postgis"
      - name: stac-fastapi-pgstac
        image: ghcr.io/stac-utils/stac-fastapi:main-pgstac
        command: ["uvicorn", "stac_fastapi.pgstac.app:app", "--host", "0.0.0.0", "--port", "8080"]
        readinessProbe:
          exec:
            command:
            - apt update
            - apt install -y procps
            - if [ 1 -eq `ps aux |grep uvicorn|grep 8080 |wc -l` ]; then exit 0; else exit 1; fi
          initialDelaySeconds: 30
          periodSeconds: 30
        ports:
          - containerPort: 8080
        env:
        - name: APP_HOST
          value: "0.0.0.0"
        - name: ENVIRONMENT
          value: "local"
        - name: POSTGRES_USER
          value: "username"
        - name: POSTGRES_PASS
          value: "password"
        - name: POSTGRES_DBNAME
          value: "postgis"
        - name: POSTGRES_HOST_READER
          value: "localhost"
        - name: POSTGRES_HOST_WRITER
          value: "localhost"
        - name: POSTGRES_PORT
          value: "5432"
        - name: WEB_CONCURRENCY
          value: "10"
        - name: VSI_CACHE
          value: "TRUE"
        - name: GDAL_HTTP_MERGE_CONSECUTIVE_RANGES
          value: "YES"
        - name: GDAL_DISABLE_READDIR_ON_OPEN
          value: "EMPTY_DIR"
        - name: DB_MIN_CONN_SIZE
          value: "1"
        - name: DB_MAX_CONN_SIZE
          value: "1"
        - name: USE_API_HYDRATE
          value: "True"

---
apiVersion: v1
kind: Service
metadata:
  name: stac
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: stac
  selector:
    app: stac